name: Lint (Python)

on: [ push, pull_request ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: "Lint CLI"
        uses: chartboost/ruff-action@v1
        with:
          src: "./src/cli"
      - name: "Lint Explorer"
        uses: chartboost/ruff-action@v1
        with:
          src: "./src/explorer"