name: Lint (Python)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Linter (Ruff)
        uses: chartboost/ruff-action@v1
      - name: Run Formatter (Black)
        uses: psf/black@stable